### PR TITLE
[1393][IMP]auth_signup_nrq: pre-commit, README

### PR DESCRIPTION
**Pull request by Ryoko04**
Task [1393](https://www.quartile.co/web#id=1393&action=771&model=project.task&view_type=form&menu_id=505)

Just added readme. No other changes.

### CODE REVIEW

**Review by yostashiro — COMMENTED** [review]
Doesn't this file get updated when you run pre-commit?

https://github.com/qrtl/nrq-custom/blob/118a78b52a443e247e77594e57d212754500b384/auth_signup_nrq/views/res_users_views.xml

**Comment by Ryoko04** [comment]
@yostashiro Sorry, I forgot updating .pre-commit-config.yaml before pre-commit. I ran pre-commit.

**Review by yostashiro — CHANGES_REQUESTED** [review]
@Ryoko04 Please remove the files from  hr_timesheet_adj in this PR.

**Comment by Ryoko04** [comment]
@yostashiro Sorry, again. I fixed it.

**Review by yostashiro — APPROVED** [review]
LGTM 👍

**Pull request merged**
