### PR TITLE
[T932][FIX] Moved Attedence position under summery tab #170

### PR DESCRIPTION
**Pull request by YogeshMahera-SerpentCS**
TASK #[932](https://www.quartile.co/web#view_type=form&model=project.task&id=932&active_id=932&menu_id=)

#170

### CODE REVIEW

**Comment by YogeshMahera-SerpentCS** [comment]
The Travis is going to fail due to this field `analytic_type_id`
https://github.com/qrtl/nrq-custom/blob/10.0/account_analytic_profit_loss_analysis/views/project_timesheet_view.xml#L10

Actual I have checked in py to search this field in this model `hr_timesheet_sheet.sheet.day` but seems I have not found even the inherit model. 

but in same module I found the comment

`    # we cannot make this field required at model level because that would
    # interfere the record creation from HrTimesheetSheet thru JS`

I am not sure what the above message is going share.

@yostashiro @TimLai125  Can you please help me here ?

**Comment by yostashiro** [comment]
@YogeshMahera-SerpentCS I am not sure why Travis fails but maybe you can try adding account_analytic_profit_loss_analysis as a dependency and see if that works around the issue?

**Comment by YogeshMahera-SerpentCS** [comment]
Hi @TimLai125 I did some changes on ` account_analytic_profit_loss_analysis` module now the travis is going to be pass, can you please check the file changes?

**Comment by yostashiro** [comment]
Good catch, @YogeshMahera-SerpentCS !

**Review by TimLai125 — APPROVED** [review]
LGTM!

**Pull request merged**
